<?php

namespace App\Domain\TechnicalInfo\Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use App\Models\Heater;

class HeaterSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */


    public function run()
    {

        for ($i=0;$i<10;$i++)
        {
            DB::table('heaters')->insert([
            'brand' =>  Str::random(10),
            'series' => Str::random(10),
            'series_image' =>  Str::random(10),
            'unit_type' => Str::random(10),
            'error_code_list' => Str::random(10),
            'voltage_checks' => Str::random(10),
            'npa' => Str::random(10),
            'spec_sheet' => Str::random(10),
            'owners_guide' => Str::random(10),
            'installation_manual' => Str::random(10),
            'parts_list' => Str::random(10),
            'certification' => Str::random(10),
            'field_manual' => Str::random(10),
            'service_manual' => Str::random(10),
            'service_manual_hot_water_capabilities' => Str::random(10),
            'service_manual_pressure_loss_chart' => Str::random(10),
            'service_manual_components' => Str::random(10),
            'service_manual_operating_principal' => Str::random(10),
            'service_manual_operation_flow' => Str::random(10),
            'service_manual_wiring_diagram' => Str::random(10),
            'service_manual_error_code_and_checkpoints' => Str::random(10),
            'service_manual_circuit_board_checkpoints' => Str::random(10),
            'service_manual_error_descriptions' => Str::random(10),
            'service_manual_maintenance' => Str::random(10),
            'service_manual_circuit_board_replacement' => Str::random(10),
            'service_manual_fan_motor_calibration' => Str::random(10),
            'service_manual_neutralizer_replacement' => Str::random(10),
            'service_manual_manifold_pressures' => Str::random(10),
            'service_manual_change_default_temperatures' => Str::random(10),
            'service_manual_condensate_drain_line' => Str::random(10),
            'residential_or_commercial' => Str::random(10),
            'install_location' => Str::random(10),
            'exhaust_type' => Str::random(10),
            'exhaust_type_l1' => '',
            'max_flow_rate' => Str::random(10),
            'max_flow_rate_l1' => '',
            'flow_rate50_deg_f_rise' => Str::random(10),
            'flow_rate80_deg_f_rise' => Str::random(10),
            'temperature_range' => Str::random(10),
            'temper_range_l1' => '',
            'production_status' => Str::random(10),
            'production_status_l1' => '',
            'condensing'  => Str::random(10),
            'condensing_l1' => '',
            'minimum_activation_flow_rate' => Str::random(10),
        'minimum_activation_flow_rate_l1' => '',
        'water_quality' => Str::random(10),
        'water_quality_l1' => '',
        'water_quality_l2' => '',
        'freeze_protection' => Str::random(10),
        'freeze_protection_rating_indoor_temp' => Str::random(10),
        'freeze_protection_rating_outdoor_temp' => Str::random(10),
        'freeze_protection_rating_outdoor_temp_l1' => '',
        'recirculation_compatible' => Str::random(10),
        'recirculation_l1' => '',
        'recirculation_l2' => '',
        'new_generation_model_number' => Str::random(10),
        'previous_name' => Str::random(10),
        'heater_image' => Str::random(10),
        'available_temperature_settings_with_remote' => Str::random(10),
        'default_temperature_setting_without_remote' => Str::random(10),
        'default_temperature_program_setting_options_without_remote' => Str::random(10),
        'production_date_range' => Str::random(10),
        'min_gas_input_btu' => Str::random(10),
        'max_gas_input_btu' => Str::random(10),
        'height_in' => Str::random(10),
        'width_in' => Str::random(10),
        'depth_in' => Str::random(10),
        'depth_l1' => '',
        'weight_lbs' => Str::random(10),
        'thermal_efficiency' => Str::random(10),
        'energy_factor' => Str::random(10),
        'energy_factor_l1' => '',
        'afue' => Str::random(10),
        'quickconnect_compatible' => Str::random(10),
        'quickconnect_l1' => '',
        'quickconnect_l2' => '',
        'cold_water_connection_size_in' => Str::random(10),
        'hot_water_connection_size_in' => Str::random(10),
        'gas_connection_size_in' => Str::random(10),
        'power_supply' => Str::random(10),
        'current_draw_a' => Str::random(10),
        'current_draw_l1' => '',
        'exhaust_vent_diameter_requirements' => Str::random(10),
        'exhaust_vent_material_requirements' => Str::random(10),
        'max_vent_length_with1_elbow' => Str::random(10),
        'max_vent_length_l1' => '',
        'vent_termination_clearances_to_any_building_opening_ft' => Str::random(10),
        'vent_termination_l1' => '',
        'gas_supply_pressure_range' => Str::random(10),
        'gas_supply_pressure_range_l1' => '',
        'min_gas_line_size' => Str::random(10),
        'min_gas_line_size_l1' => '',
        'water_pressure_rating_psi' => Str::random(10),
        'case_clearances_in' => Str::random(10),
        'case_clearances_l1' => '',
        'combustion_air_requirements_using_indoor_air' => Str::random(10),
        'combustion_air_requirements_using_outdoor_air' => Str::random(10),
        'combustion_air_outdoor_l1' => '',
        'head_loss_at2_gpm' => Str::random(10),
        'head_loss_l1' => '',
        'cold_connection_height' => Str::random(10),
        'power_consumption_wout_freeze_prevention' => Str::random(10),
        'power_consumption_wfreeze_prevention' => Str::random(10),
        'flow_meter_alarm' => Str::random(10),
        'service_reminder' => Str::random(10),
        'condensate_handling_method' => Str::random(10),
        'noise_rating_db' => Str::random(10),
        'tested_to_ul_computer_controlled_safety_standards' => Str::random(10),
        'flame_sensor' => Str::random(10),
        'high_limit_switch' => Str::random(10),
        'lightning_protection' => Str::random(10),
        'overheat_cutoff_fuse' => Str::random(10),
        'temperature_lockout' => Str::random(10),
        'ignition_type' => Str::random(10),
        'case_material' => Str::random(10),
        'colorfinish' => Str::random(10),
        'flue_collar_material' => Str::random(10),
        'primary_heat_exchanger_material' => Str::random(10),
        'secondary_heat_exchanger_material' => Str::random(10),
        'mounting_type' => Str::random(10),
        'package_contents' => Str::random(10),
        'water_holding_capacity' => Str::random(10),
        'keypadthermostat_display' => Str::random(10),
        'keypadthermostat_display_l1' => '',
        'compatible_remote_controller_part_num_id' => Str::random(10),
        'compatible_remote_controller_part_num_l1' => '',
        'isolator_valve_part_num_id' => Str::random(10),
        'isolator_valve_part_num_l1' => '',
        'freeze_protection_kit_accessory' => Str::random(10),
        'freeze_protection_kit_accessory_l1' => '',
        'outdoor_vent_cap_part_num_id' => Str::random(10),
        'outdoor_vent_cap_part_num_l1' => '',
        'pipe_cover_part_num_id' => Str::random(10),
        'pipe_cover_part_num_l1' => '',
        'recess_box_part_num_id' => Str::random(10),
        'recess_box_part_num_l1' => '',
        'high_elevation_adjustment' => Str::random(10),
        'high_elevation_adjustment_l1' => '',
        'quickconnect_cord_part_num_id' => Str::random(10),
        'system_controller_compatible' => Str::random(10),
        'system_controller_compatible_l1' => '',
        'system_controller_part_num_id' => Str::random(10),
        'system_controller_part_num_l1' => '',
        'remote_controller_cord' => Str::random(10),
        'compatible_remote_controller_cord_part_num_id' => Str::random(10),
        'power_cord' => Str::random(10),
        'energy_star_qualified' => Str::random(10),
        'csa' => Str::random(10),
        'mobile_home' => Str::random(10),
        'nsf' => Str::random(10),
        'scaqmd20_ppm' => Str::random(10),
        'scaqmd55_ppm' => Str::random(10),
        'upc' => Str::random(10),
        'energy_guide_est_yearly_energy_use' => Str::random(10),
        'energy_guide_est_yearly_energy_use_l1' => '',
        'energy_guide_est_yearly_operating_cost' => Str::random(10),
        'upc_low_lead' => Str::random(10),
        'asme_hlw' => Str::random(10),
        'asme_h' => Str::random(10),
        'asme_nb' => Str::random(10),
        'heat_exchanger_warranty_wout_recirculation' => Str::random(10),
        'heat_exchanger_warranty_wrecirculation' => Str::random(10),
        'parts_warranty' => Str::random(10),
        'labor_warranty' => Str::random(10),
        'laborwarrantyl1' => '',
        'name' => Str::random(10),
        'parts_list_file' => Str::random(10)

        ]);
        }
    }
}
