<?php

namespace App\Domain\TechnicalInfo\Database\Factories;

use App\Models\Heater;
use Illuminate\Database\Eloquent\Factories\Factory;
use Illuminate\Support\Str;

class HeaterFactory extends Factory
{
    /**
     * The name of the factory's corresponding model.
     *
     * @var string
     */
    protected $model = Heater::class;

    /**
     * Define the model's default state.
     *
     * @return array
     */
    public function definition()
    {
        return [
            'id' => $this->faker->numberBetween(1,100),
            'brand' => $this->faker->text,
            'series' => $this->faker->text,
            'series_image' => $this->faker->text,
            'unit_type' => $this->faker->text,
            'error_code_list' => $this->faker->text,
            'voltage_checks' => $this->faker->numberBetween(1,100),
            'npa' => $this->faker->text,
            'spec_sheet' => $this->faker->numberBetween(1,100),
            'owners_guide' => $this->faker->numberBetween(1,100),
            'installation_manual' => $this->faker->numberBetween(1,100),
            'parts_list' => $this->faker->numberBetween(1,100),
            'certification' => $this->faker->numberBetween(1,100),
            'field_manual' => $this->faker->numberBetween(1,100),
            'service_manual' => $this->faker->numberBetween(1,100),
            'service_manual_hot_water_capabilities' => $this->faker->numberBetween(1,100),
            'service_manual_hot_water_capabilities' => $this->faker->numberBetween(1,100),
            'service_manual_pressure_loss_chart' => $this->faker->numberBetween(1,100),
            'service_manual_components' => $this->faker->numberBetween(1,100),
            'service_manual_operating_principal' => $this->faker->numberBetween(1,100),
            'service_manual_operation_flow' => $this->faker->numberBetween(1,100),
            'service_manual_wiring_diagram' => $this->faker->numberBetween(1,100),
            'service_manual_error_code_and_checkpoints' => $this->faker->numberBetween(1,100),
            'service_manual_circuit_board_checkpoints' => $this->faker->numberBetween(1,100),
            'service_manual_error_descriptions' => $this->faker->numberBetween(1,100),
            'service_manual_maintenance' => $this->faker->numberBetween(1,100),
            'service_manual_circuit_board_replacement' => $this->faker->numberBetween(1,100),
            'service_manual_fan_motor_calibration' => $this->faker->numberBetween(1,100),
            'service_manual_neutralizer_replacement' => $this->faker->numberBetween(1,100),
            'service_manual_manifold_pressures' => $this->faker->numberBetween(1,100),
            'service_manual_change_default_temperatures' => $this->faker->numberBetween(1,100),
            'service_manual_condensate_drain_line' => $this->faker->numberBetween(1,100),
            'residential_or_commercial' => $this->faker->text,
            'install_location' => $this->faker->text,
            'exhaust_type_l1' => $this->faker->numberBetween(1,100),
            'max_flow_rate' => $this->faker->text,
            'max_flow_rate_l1' => $this->faker->numberBetween(1,100),
            'flow_rate50_deg_f_rise' => $this->faker->text,
            'flow_rate80_deg_f_rise' => $this->faker->text,
            'temperature_range' => $this->faker->text,
            'temper_range_l1' => $this->faker->numberBetween(1,100),
            'production_status' => $this->faker->text,
            'production_status_l1' => $this->faker->numberBetween(1,100),
            'condensing' => $this->faker->text,
            'condensing_l1' => $this->faker->numberBetween(1,100),
            'minimum_activation_flow_rate' => $this->faker->text,
            'minimum_activation_flow_rate_l1' => $this->faker->numberBetween(1,100),
            'water_quality' => $this->faker->text,
            'water_quality_l1' => $this->faker->numberBetween(1,100),
            'water_quality_l2' => $this->faker->numberBetween(1,100),
            'freeze_protection' => $this->faker->text,
            'freeze_protection_rating_indoor_temp' => $this->faker->text,
            'freeze_protection_rating_outdoor_temp' => $this->faker->text,
            'freeze_protection_rating_outdoor_temp_l1' => $this->faker->numberBetween(1,100),
            'recirculation_compatible' => $this->faker->text,
            'recirculation_l1' => $this->faker->numberBetween(1,100),
            'recirculation_l2' => $this->faker->numberBetween(1,100),
            'new_generation_model_number' => $this->faker->text,
            'previous_name' => $this->faker->text,
            'heater_image' => $this->faker->numberBetween(1,100),
            'available_temperature_settings_with_remote' => $this->faker->text,
            'default_temperature_setting_without_remote' => $this->faker->text,
            'default_temperature_program_setting_options_without_remote' => $this->faker->text,
            'production_date_range' => $this->faker->text,
            'min_gas_input_btu' => $this->faker->text,
            'max_gas_input_btu' => $this->faker->text,
            'height_in' => $this->faker->text,
            'width_in' => $this->faker->text,
            'depth_in' => $this->faker->text,
            'depth_l1' => $this->faker->numberBetween(1,100),
            'weight_lbs' => $this->faker->text,
            'thermal_efficiency' => $this->faker->text,
            'energy_factor' => $this->faker->text,
            'energy_factor_l1' => $this->faker->numberBetween(1,100),
            'afue' => $this->faker->text,
            'quickconnect_compatible' => $this->faker->text,
            'quickconnect_l1' => $this->faker->numberBetween(1,100),
            'quickconnect_l2' => $this->faker->numberBetween(1,100),
            'cold_water_connection_size_in' => $this->faker->text,
            'hot_water_connection_size_in' => $this->faker->text,
            'gas_connection_size_in' => $this->faker->text,
            'power_supply' => $this->faker->text,
            'current_draw_a' => $this->faker->text,
            'current_draw_l1' => $this->faker->numberBetween(1,100),
            'exhaust_vent_diameter_requirements' => $this->faker->text,
            'exhaust_vent_material_requirements' => $this->faker->text,
            'max_vent_length_with1_elbow' => $this->faker->text,
            'max_vent_length_l1' => $this->faker->numberBetween(1,100),
            'vent_termination_clearances_to_any_building_opening_ft' => $this->faker->text,
            'vent_termination_l1' => $this->faker->numberBetween(1,100),
            'gas_supply_pressure_range' => $this->faker->text,
            'gas_supply_pressure_range_l1' => $this->faker->numberBetween(1,100),
            'min_gas_line_size' => $this->faker->text,
            'min_gas_line_size_l1' => $this->faker->numberBetween(1,100),
            'water_pressure_rating_psi' => $this->faker->text,
            'case_clearances_in' => $this->faker->text,
            'case_clearances_l1' => $this->faker->numberBetween(1,100),
            'combustion_air_requirements_using_indoor_air' => $this->faker->text,
            'combustion_air_requirements_using_outdoor_air' => $this->faker->text,
            'combustion_air_outdoor_l1' => $this->faker->numberBetween(1,100),
            'head_loss_at2_gpm' => $this->faker->text,
            'head_loss_l1' => $this->faker->numberBetween(1,100),
            'cold_connection_height' => $this->faker->text,
            'power_consumption_wout_freeze_prevention' => $this->faker->text,
            'power_consumption_wfreeze_prevention' => $this->faker->text,
            'flow_meter_alarm' => $this->faker->text,
            'service_reminder' => $this->faker->text,
            'condensate_handling_method' => $this->faker->text,
            'noise_rating_db' => $this->faker->text,
            'tested_to_ul_computer_controlled_safety_standards' => $this->faker->text,
            'flame_sensor' => $this->faker->text,
            'high_limit_switch' => $this->faker->text,
            'lightning_protection' => $this->faker->text,
            'overheat_cutoff_fuse' => $this->faker->text,
            'temperature_lockout' => $this->faker->text,
            'ignition_type' => $this->faker->text,
            'case_material' => $this->faker->text,
            'colorfinish' => $this->faker->text,
            'flue_collar_material' => $this->faker->text,
            'primary_heat_exchanger_material' => $this->faker->text,
            'secondary_heat_exchanger_material' => $this->faker->text,
            'mounting_type' => $this->faker->text,
            'package_contents' => $this->faker->text,
            'water_holding_capacity' => $this->faker->text,
            'keypadthermostat_display' => $this->faker->text,
            'keypadthermostat_display_l1' => $this->faker->numberBetween(1,100),
            'compatible_remote_controller_part_num_l1' => $this->faker->numberBetween(1,100),
            'isolator_valve_part_num_l1' => $this->faker->numberBetween(1,100),
            'freeze_protection' => $this->faker->text,
            'freeze_protection_kit_accessory' => $this->faker->text,
            'freeze_protection_kit_accessory_l1' => $this->faker->numberBetween(1,100),
            'outdoor_vent_cap_part_num_l1' => $this->faker->numberBetween(1,100),
            'pipe_cover_part_num_l1' => $this->faker->numberBetween(1,100),
            'recess_box_part_num_l1' => $this->faker->numberBetween(1,100),
            'high_elevation_adjustment' => $this->faker->text,
            'high_elevation_adjustment_l1' => $this->faker->numberBetween(1,100),
            'system_controller_compatible' => $this->faker->text,
            'system_controller_compatible_l1' => $this->faker->numberBetween(1,100),
            'system_controller_part_num_l1' => $this->faker->numberBetween(1,100),
            'remote_controller_cord' => $this->faker->text,
            'power_cord' => $this->faker->text,
            'energy_star_qualified' => $this->faker->text,
            'csa' => $this->faker->text,
            'mobile_home' => $this->faker->text,
            'nsf' => $this->faker->text,
            'scaqmd20_ppm' => $this->faker->text,
            'scaqmd55_ppm' => $this->faker->text,
            'upc' => $this->faker->text,
            'energy_guide_est_yearly_energy_use' => $this->faker->text,
            'energy_guide_est_yearly_energy_use_l1' => $this->faker->text,
            'energy_guide_est_yearly_operating_cost' => $this->faker->text,
            'upc_low_lead' => $this->faker->text,
            'asme_hlw' => $this->faker->text,
            'asme_h' => $this->faker->text,
            'asme_nb' => $this->faker->text,
            'heat_exchanger_warranty_wout_recirculation' => $this->faker->text,
            'heat_exchanger_warranty_wrecirculation' => $this->faker->text,
            'parts_warranty' => $this->faker->text,
            'labor_warranty' => $this->faker->text,
            'laborwarrantyl1' => $this->faker->text,
            'name' => $this->faker->text,
            'parts_list_file' => $this->faker->numberBetween(1,100),
        ];
    }
}
