<?php

namespace App\Nova\Filters;

use Illuminate\Http\Request;
use Laravel\Nova\Filters\Filter;

class ArchiveStatus extends Filter
{
    /**
     * The filter's component.
     *
     * @var string
     */
    public $component = 'select-filter';

    /**
     * Apply the filter to the given query.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Illuminate\Database\Eloquent\Builder  $query
     * @param  mixed  $value
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function apply(Request $request, $query, $value)
    {
        ray($value);

        if ($value == 'all') {
            return $query;
        }

        if ($value == 'archived') {
            return $query->whereNotNull('archived_at');
        }

        return $query->whereNull('archived_at');
    }

    /**
     * Get the filter's available options.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function options(Request $request)
    {
        return [
            'All' => 'all',
            'Archived' => 'archived',
            'Unarchived' => 'unarchived',
        ];
    }

    public function default()
    {
        return 'unarchived'; // TODO: Change the autogenerated stub
    }
}
