<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateHeatersTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('heaters', function (Blueprint $table) {
            $table->bigInteger('id', true);
            $table->text('brand')->nullable();
            $table->text('series')->nullable();
            $table->text('series_image')->nullable();
            $table->text('unit_type')->nullable();
            $table->text('error_code_list')->nullable();
            $table->text('voltage_checks')->nullable();
            $table->text('npa')->nullable();
            $table->text('spec_sheet')->nullable();
            $table->text('owners_guide')->nullable();
            $table->text('installation_manual')->nullable();
            $table->text('parts_list')->nullable();
            $table->text('certification')->nullable();
            $table->text('field_manual')->nullable();
            $table->text('service_manual')->nullable();
            $table->text('service_manual_hot_water_capabilities')->nullable();
            $table->text('service_manual_pressure_loss_chart')->nullable();
            $table->text('service_manual_components')->nullable();
            $table->text('service_manual_operating_principal')->nullable();
            $table->text('service_manual_operation_flow')->nullable();
            $table->text('service_manual_wiring_diagram')->nullable();
            $table->text('service_manual_error_code_and_checkpoints')->nullable();
            $table->text('service_manual_circuit_board_checkpoints')->nullable();
            $table->text('service_manual_error_descriptions')->nullable();
            $table->text('service_manual_maintenance')->nullable();
            $table->text('service_manual_circuit_board_replacement')->nullable();
            $table->text('service_manual_fan_motor_calibration')->nullable();
            $table->text('service_manual_neutralizer_replacement')->nullable();
            $table->text('service_manual_manifold_pressures')->nullable();
            $table->text('service_manual_change_default_temperatures')->nullable();
            $table->text('service_manual_condensate_drain_line')->nullable();
            $table->text('residential_or_commercial')->nullable();
            $table->text('install_location')->nullable();
            $table->text('exhaust_type')->nullable();
            $table->text('exhaust_type_l1')->nullable();
            $table->text('max_flow_rate')->nullable();
            $table->text('max_flow_rate_l1')->nullable();
            $table->text('flow_rate50_deg_f_rise')->nullable();
            $table->text('flow_rate80_deg_f_rise')->nullable();
            $table->text('temperature_range')->nullable();
            $table->text('temper_range_l1')->nullable();
            $table->text('production_status')->nullable();
            $table->text('production_status_l1')->nullable();
            $table->text('condensing')->nullable();
            $table->text('condensing_l1')->nullable();
            $table->text('minimum_activation_flow_rate')->nullable();
            $table->text('minimum_activation_flow_rate_l1')->nullable();
            $table->text('water_quality')->nullable();
            $table->text('water_quality_l1')->nullable();
            $table->text('water_quality_l2')->nullable();
            $table->text('freeze_protection')->nullable();
            $table->text('freeze_protection_rating_indoor_temp')->nullable();
            $table->text('freeze_protection_rating_outdoor_temp')->nullable();
            $table->text('freeze_protection_rating_outdoor_temp_l1')->nullable();
            $table->text('recirculation_compatible')->nullable();
            $table->text('recirculation_l1')->nullable();
            $table->text('recirculation_l2')->nullable();
            $table->text('new_generation_model_number')->nullable();
            $table->text('previous_name')->nullable();
            $table->text('heater_image')->nullable();
            $table->text('available_temperature_settings_with_remote')->nullable();
            $table->text('default_temperature_setting_without_remote')->nullable();
            $table->text('default_temperature_program_setting_options_without_remote')->nullable();
            $table->text('production_date_range')->nullable();
            $table->text('min_gas_input_btu')->nullable();
            $table->text('max_gas_input_btu')->nullable();
            $table->text('height_in')->nullable();
            $table->text('width_in')->nullable();
            $table->text('depth_in')->nullable();
            $table->text('depth_l1')->nullable();
            $table->text('weight_lbs')->nullable();
            $table->text('thermal_efficiency')->nullable();
            $table->text('energy_factor')->nullable();
            $table->text('energy_factor_l1')->nullable();
            $table->text('afue')->nullable();
            $table->text('quickconnect_compatible')->nullable();
            $table->text('quickconnect_l1')->nullable();
            $table->text('quickconnect_l2')->nullable();
            $table->text('cold_water_connection_size_in')->nullable();
            $table->text('hot_water_connection_size_in')->nullable();
            $table->text('gas_connection_size_in')->nullable();
            $table->text('power_supply')->nullable();
            $table->text('current_draw_a')->nullable();
            $table->text('current_draw_l1')->nullable();
            $table->text('exhaust_vent_diameter_requirements')->nullable();
            $table->text('exhaust_vent_material_requirements')->nullable();
            $table->text('max_vent_length_with1_elbow')->nullable();
            $table->text('max_vent_length_l1')->nullable();
            $table->text('vent_termination_clearances_to_any_building_opening_ft')->nullable();
            $table->text('vent_termination_l1')->nullable();
            $table->text('gas_supply_pressure_range')->nullable();
            $table->text('gas_supply_pressure_range_l1')->nullable();
            $table->text('min_gas_line_size')->nullable();
            $table->text('min_gas_line_size_l1')->nullable();
            $table->text('water_pressure_rating_psi')->nullable();
            $table->text('case_clearances_in')->nullable();
            $table->text('case_clearances_l1')->nullable();
            $table->text('combustion_air_requirements_using_indoor_air')->nullable();
            $table->text('combustion_air_requirements_using_outdoor_air')->nullable();
            $table->text('combustion_air_outdoor_l1')->nullable();
            $table->text('head_loss_at2_gpm')->nullable();
            $table->text('head_loss_l1')->nullable();
            $table->text('cold_connection_height')->nullable();
            $table->text('power_consumption_wout_freeze_prevention')->nullable();
            $table->text('power_consumption_wfreeze_prevention')->nullable();
            $table->text('flow_meter_alarm')->nullable();
            $table->text('service_reminder')->nullable();
            $table->text('condensate_handling_method')->nullable();
            $table->text('noise_rating_db')->nullable();
            $table->text('tested_to_ul_computer_controlled_safety_standards')->nullable();
            $table->text('flame_sensor')->nullable();
            $table->text('high_limit_switch')->nullable();
            $table->text('lightning_protection')->nullable();
            $table->text('overheat_cutoff_fuse')->nullable();
            $table->text('temperature_lockout')->nullable();
            $table->text('ignition_type')->nullable();
            $table->text('case_material')->nullable();
            $table->text('colorfinish')->nullable();
            $table->text('flue_collar_material')->nullable();
            $table->text('primary_heat_exchanger_material')->nullable();
            $table->text('secondary_heat_exchanger_material')->nullable();
            $table->text('mounting_type')->nullable();
            $table->text('package_contents')->nullable();
            $table->text('water_holding_capacity')->nullable();
            $table->text('keypadthermostat_display')->nullable();
            $table->text('keypadthermostat_display_l1')->nullable();
            $table->text('compatible_remote_controller_part_num_id')->nullable();
            $table->text('compatible_remote_controller_part_num_l1')->nullable();
            $table->text('isolator_valve_part_num_id')->nullable();
            $table->text('isolator_valve_part_num_l1')->nullable();
            $table->text('freeze_protection_kit_accessory')->nullable();
            $table->text('freeze_protection_kit_accessory_l1')->nullable();
            $table->text('outdoor_vent_cap_part_num_id')->nullable();
            $table->text('outdoor_vent_cap_part_num_l1')->nullable();
            $table->text('pipe_cover_part_num_id')->nullable();
            $table->text('pipe_cover_part_num_l1')->nullable();
            $table->text('recess_box_part_num_id')->nullable();
            $table->text('recess_box_part_num_l1')->nullable();
            $table->text('high_elevation_adjustment')->nullable();
            $table->text('high_elevation_adjustment_l1')->nullable();
            $table->text('quickconnect_cord_part_num_id')->nullable();
            $table->text('system_controller_compatible')->nullable();
            $table->text('system_controller_compatible_l1')->nullable();
            $table->text('system_controller_part_num_id')->nullable();
            $table->text('system_controller_part_num_l1')->nullable();
            $table->text('remote_controller_cord')->nullable();
            $table->text('compatible_remote_controller_cord_part_num_id')->nullable();
            $table->text('power_cord')->nullable();
            $table->text('energy_star_qualified')->nullable();
            $table->text('csa')->nullable();
            $table->text('mobile_home')->nullable();
            $table->text('nsf')->nullable();
            $table->text('scaqmd20_ppm')->nullable();
            $table->text('scaqmd55_ppm')->nullable();
            $table->text('upc')->nullable();
            $table->text('energy_guide_est_yearly_energy_use')->nullable();
            $table->text('energy_guide_est_yearly_energy_use_l1')->nullable();
            $table->text('energy_guide_est_yearly_operating_cost')->nullable();
            $table->text('upc_low_lead')->nullable();
            $table->text('asme_hlw')->nullable();
            $table->text('asme_h')->nullable();
            $table->text('asme_nb')->nullable();
            $table->text('heat_exchanger_warranty_wout_recirculation')->nullable();
            $table->text('heat_exchanger_warranty_wrecirculation')->nullable();
            $table->text('parts_warranty')->nullable();
            $table->text('labor_warranty')->nullable();
            $table->text('laborwarrantyl1')->nullable();
            $table->text('name')->nullable();
            $table->text('parts_list_file')->nullable();
            $table->string('part_id')->nullable();
            $table->string('model_no')->nullable();
            $table->string('model_type')->nullable();
            $table->string('drawings')->nullable();
            $table->string('fp2')->nullable();
            $table->string('warrantyindex')->nullable();
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('heaters');
    }
}
